In [1]:
from sparsemax import Sparsemax
import torch
import torch.nn as nn

sparsemax = Sparsemax(dim=-1)
softmax = torch.nn.Softmax(dim=-1)

logits = torch.randn(2, 3, 5)
logits.requires_grad = True
print("\nLogits")
print(logits)

softmax_probs = softmax(logits)
print("\nSoftmax probabilities")
print(softmax_probs)

sparsemax_probs = sparsemax(logits)
print("\nSparsemax probabilities")
print(sparsemax_probs)


Logits
tensor([[[-1.2688,  0.9123,  0.0554,  0.8725,  0.0765],
         [-0.7079,  0.0612, -0.0700,  0.2600,  0.5129],
         [-2.1699,  1.7280, -0.9203,  0.7612, -0.7385]],

        [[-0.5817,  0.1357,  0.7026, -0.1495, -1.8451],
         [ 0.2139,  0.0166, -0.4692, -0.2892,  0.3577],
         [ 0.7514, -0.0494,  1.0021, -0.3586,  2.0276]]], requires_grad=True)

Softmax probabilities
tensor([[[0.0385, 0.3411, 0.1448, 0.3278, 0.1479],
         [0.0903, 0.1949, 0.1709, 0.2377, 0.3061],
         [0.0130, 0.6426, 0.0455, 0.2444, 0.0545]],

        [[0.1179, 0.2415, 0.4257, 0.1816, 0.0333],
         [0.2448, 0.2009, 0.1236, 0.1480, 0.2826],
         [0.1504, 0.0676, 0.1933, 0.0496, 0.5391]]],
       grad_fn=<SoftmaxBackward0>)

Sparsemax probabilities
tensor([[[0.0000, 0.5199, 0.0000, 0.4801, 0.0000],
         [0.0000, 0.1165, 0.0000, 0.3153, 0.5682],
         [0.0000, 0.9834, 0.0000, 0.0166, 0.0000]],

        [[0.0000, 0.2165, 0.7835, 0.0000, 0.0000],
         [0.3511, 0.1539, 0.0000,

In [13]:
logits

tensor([[[-1.2688,  0.9123,  0.0554,  0.8725,  0.0765],
         [-0.7079,  0.0612, -0.0700,  0.2600,  0.5129],
         [-2.1699,  1.7280, -0.9203,  0.7612, -0.7385]],

        [[-0.5817,  0.1357,  0.7026, -0.1495, -1.8451],
         [ 0.2139,  0.0166, -0.4692, -0.2892,  0.3577],
         [ 0.7514, -0.0494,  1.0021, -0.3586,  2.0276]]], requires_grad=True)

In [22]:
my_values = [-1.2688,  0.9123,  0.0554,  0.8725,  0.0765]
sparsemax(torch.tensor([my_values])).tolist()[0]

[0.0, 0.5198999643325806, 0.0, 0.48009997606277466, 0.0]

In [15]:
sparsemax_probs[0, 0, :]

tensor([0.0000, 0.5199, 0.0000, 0.4801, 0.0000], grad_fn=<SliceBackward0>)